# Generated by Django 4.0.3 on 2022-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App', '0002_registered_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
